### ISSUE TITLE
Faster Form Loading problem in 4.2

### ISSUE THREAD

**Issue by ahmedihs** [OpenSRP/opensrp-client#137] opened 2016-01-15 09:24 UTC
@koros  Faster forms are loadding but showing only white page instead of the form . please look into it.

**Comment by koros** [comment] 2016-01-22 07:59
Hi @ahmedihs i think the issue is now fixed confirm on your end

**Comment by ahmedihs** [comment] 2016-01-22 10:00
thanks @koros  the issue is resolved

**Closed** 2016-01-22 10:00 UTC
Labels: bug, Functional Requirement, High Priority
